version: '3.7'

services:
  backend:
    container_name: minaserver
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

    #command: npm run start:dev
    env_file:
      - .env
    networks:
      - minaservernet
    depends_on:
      - redis
      - database
#    command:  sh -c "yarn migration:run && yarn build && yarn start:dev"

    command:  sh -c "yarn build && yarn start:dev"
  redis:
    container_name: minaserver-redis
    image: redis:5
    networks:
      - minaservernet
  database:
    container_name: minaserver-db
    networks:
      - minaservernet
    image: postgres:11.13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    #      PG_DATA: /var/lib/postgresql/data_graphql/
    volumes:
      #use this to easily share db volume with other users
      - minaserver:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

networks:
  minaservernet:
volumes:
  minaserver:
  node_mod: